poll:
  agent-name: east-1
  poll-key: 1234567ABC
quarkus:
  http:
    port: 8090
  log:
    category:
      "io.levysworks":
        level: DEBUG
    level: INFO
  rabbitmqclient:
    username: user
    password: pass
    hostname: localhost
    port: 5672
    virtual-host: /