poll:
  agent-name: east-1
quarkus:
  http:
    port: 8090
  log:
    category:
      "io.levysworks":
        level: DEBUG
    level: INFO
  rabbitmqclient:
    username: user
    password: pass
    hostname: 192.168.1.232
    port: 5672
    virtual-host: /